name = "wrangler-tutorial"
main = "src/index.ts"
compatibility_date = "2023-10-30"

account_id = "ea23e12e220c8f6b189bd6a8cb1a9802"

r2_buckets =[
{binding = "R2_BUCKET",bucket_name = "country-flags" , preview_bucket_name = "worker-r2-dev" }

]